export const ERROR_CODES = {
    // Common
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    NOT_FOUND: 'NOT_FOUND',
    FORBIDDEN: 'FORBIDDEN',
    INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',

    // Auth
    MISSING_TOKEN: 'MISSING_TOKEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
    USER_NOT_FOUND: 'USER_NOT_FOUND',

    // Category
    CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
    DUPLICATE_CATEGORY: 'DUPLICATE_CATEGORY',

    // Task
    TASK_NOT_FOUND: 'TASK_NOT_FOUND',
};